import Verse from "./Verse";

export default function Chapter() {
  const verses = [
    `No princípio era o Verbo, e o Verbo estava com Deus, e o Verbo era Deus.`,
    `Ele estava no princípio com Deus.`,
    `Todas as coisas foram feitas por ele, e, sem ele, nada do que foi feito se fez.`,
    `A vida estava nele e a vida era a luz dos homens.`,
    `A luz resplandece nas trevas, e as trevas não prevaleceram contra ela.`,
    `Houve um homem enviado por Deus, e o nome dele era João.`,
    `Este veio como testemunha para testificar a respeito da luz, para que todos viessem a crer por meio dele.`,
    `Ele não era a luz, mas veio para dar testemunho da luz,`,
    `a verdadeira luz, que, vinda ao mundo, ilumina toda a humanidade.`,
    `O Verbo estava no mundo, o mundo foi feito por meio dele, mas o mundo não o conheceu.`,
    `Veio para o que era seu, e os seus não o receberam.`,
    `Mas, a todos quantos o receberam, deu-lhes o poder de serem feitos filhos de Deus, a saber, aos que creem no seu nome,`,
    `os quais não nasceram do sangue, nem da vontade da carne, nem da vontade do homem, mas de Deus.`,
    `E o Verbo se fez carne e habitou entre nós, cheio de graça e de verdade, e vimos a sua glória, glória como do unigênito do Pai.`,
    `João dá testemunho a respeito dele e exclama: — Este é aquele de quem eu dizia: "Ele vem depois de mim, mas é mais importante do que eu, pois já existia antes de mim."`,
    `Porque todos nós temos recebido da sua plenitude e graça sobre graça.`,
    `Porque a lei foi dada por meio de Moisés; a graça e a verdade vieram por meio de Jesus Cristo.`,
    `Ninguém jamais viu Deus; o Deus unigênito, que está junto do Pai, é quem o revelou.`,
    `Este foi o testemunho de João, quando os judeus lhe enviaram de Jerusalém sacerdotes e levitas para perguntar: "Quem é você?"`,
    `Ele confessou e não negou; confessou: — Eu não sou o Cristo.`,
    `Diante disso, lhe perguntaram: — Quem é você, então? Você é Elias? Ele disse: — Não sou. Então perguntaram: — Você é o profeta? Ele respondeu: — Não, não sou.`,
    `Disseram-lhe, então: — Diga quem é você, para podermos dar uma resposta àqueles que nos enviaram. O que é que você diz a respeito de si mesmo?`,
    `Então ele respondeu: — Eu sou "a voz do que clama no deserto: Endireitem o caminho do Senhor", como disse o profeta Isaías.`,
    `Ora, os que haviam sido enviados eram do grupo dos fariseus.`,
    `E perguntaram a João: — Então por que você batiza, se não é o Cristo, nem Elias, nem o profeta?`,
    `João respondeu: — Eu batizo com água, mas no meio de vocês está alguém que vocês não conhecem.`,
    `Ele vem depois de mim, mas não sou digno de desamarrar as correias das suas sandálias.`,
    `Essas coisas aconteceram em Betânia, do outro lado do Jordão, onde João estava batizando.`,
    `No dia seguinte, vendo que Jesus vinha em sua direção, João disse: — Eis o Cordeiro de Deus, que tira o pecado do mundo!`,
    `Este é aquele a respeito de quem eu falava, quando disse: "Depois de mim vem um homem que é mais importante do que eu, porque já existia antes de mim."`,
    `Eu mesmo não o conhecia, mas vim batizando com água a fim de que ele fosse manifestado a Israel.`,
    `E João testemunhou, dizendo: — Vi o Espírito descer do céu como pomba e pousar sobre ele.`,
    `Eu não o conhecia; aquele, porém, que me enviou a batizar com água me disse: "Aquele sobre quem você vir descer e pousar o Espírito, esse é o que batiza com o Espírito Santo."`,
    `Pois eu mesmo vi e dou testemunho de que ele é o Filho de Deus.`,
    `No dia seguinte, João estava outra vez na companhia de dois dos seus discípulos`,
    `e, vendo Jesus passar, disse: — Eis o Cordeiro de Deus!`,
    `Os dois discípulos, ouvindo-o dizer isso, seguiram Jesus.`,
    `E Jesus, voltando-se e vendo que o seguiam, disse-lhes: — O que vocês estão procurando? Eles disseram: — Rabi, onde o senhor mora? ("Rabi" quer dizer "Mestre".)`,
    `Jesus respondeu: — Venham ver! Então eles foram, viram onde Jesus estava morando e ficaram com ele aquele dia. Eram mais ou menos quatro horas da tarde.`,
    `André, o irmão de Simão Pedro, era um dos dois que tinham ouvido o testemunho de João e seguido Jesus.`,
    `Ele encontrou primeiro o seu próprio irmão, Simão, a quem disse: — Achamos o Messias! ("Messias" quer dizer "Cristo".)`,
    `E o levou a Jesus. Jesus olhou para ele e disse: — Você é Simão, filho de João, mas agora será chamado Cefas. ("Cefas" quer dizer "Pedro".)`,
    `No dia seguinte, Jesus resolveu ir para a Galileia e encontrou Filipe, a quem disse: — Siga-me.`,
    `Esse Filipe era de Betsaida, cidade de André e de Pedro.`,
    `Filipe encontrou Natanael e lhe disse: — Achamos aquele de quem Moisés escreveu na Lei, e a quem se referiram os profetas: Jesus, o Nazareno, filho de José.`,
    `Então Natanael perguntou: — De Nazaré pode sair alguma coisa boa? Filipe respondeu: — Venha ver!`,
    `Jesus viu Natanael se aproximar e disse a respeito dele: — Eis um verdadeiro israelita, em quem não existe fingimento algum!`,
    `Natanael perguntou a Jesus: — De onde o senhor me conhece? Jesus respondeu: — Antes de Filipe chamá-lo, eu já tinha visto você debaixo da figueira.`,
    `Então Natanael exclamou: — Mestre, o senhor é o Filho de Deus! O senhor é o Rei de Israel!`,
    `Ao que Jesus lhe respondeu: — Você crê porque eu disse que tinha visto você debaixo da figueira? Pois você verá coisas maiores do que estas.`,
    `E acrescentou: — Em verdade, em verdade lhes digo que vocês verão o céu aberto e os anjos de Deus subindo e descendo sobre o Filho do Homem.`,
  ];
  return verses.map((verse, index) => (
    <Verse number={index + 1} text={verse} key={index} />
  ));
}
